import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Banner from './components/Banner'
import Buscador from './components/Buscador'
import Footer from './components/Footer'

export const metadata: Metadata = {
  title: 'Booking.com | Página no oficial Clone',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Banner />
        <Buscador />
        {children}
      
        <Footer />
      </body>
    </html>
  )
}
